### ISSUE TITLE
Questions which use escaped strings are classified as an SQL injection vulnerability

### ISSUE THREAD

**Issue by matthewfranglen** [laurent22/so-sql-injections#1]
I don't write PHP so I'm probably confused. I looked up the latest question that you had classified, which at the time of writing was:

```
04/12/2016 10:59:19:	$result = $mysqli->query("SELECT COUNT(*) FROM user WHERE benutzername ='$benutzername' AND passwort='$passwort'");
```

[This](http://stackoverflow.com/questions/40957890/post-method-always-returns-nothing) is the question and here is the context:

```php
$benutzername = $mysqli->real_escape_string(isset($_POST['PARAM_LOGIN']));
$passwort = $mysqli->real_escape_string(isset($_POST['PARAM_PASSWORT']));

$result =  $mysqli->query("SELECT COUNT(*) FROM user WHERE benutzername    ='$benutzername' AND passwort='$passwort'");
```

The two variables receive the output of `mysqli::real_escape_string` which is documented as follows:
> Escapes special characters in a string for use in an SQL statement, taking into account the current charset of the connection

http://php.net/manual/en/mysqli.real-escape-string.php

**Comment by laurent22** [comment]
Yes there are definitely same false positives in the dataset as the script currently simply checks for the existence of a `$variable` inside an SQL string. This is usually a very strong indicator that there is (or will be) an SQL injection vulnerability.

Regarding `real_escape_string`, it really only provides the illusion of safety since [it's possible to go around it](http://stackoverflow.com/a/23277864/561309). But even if the query is currently safe, it's possible that later on, another developer will append a variable to this SQL statement and forget to escape it, or maybe the format of one of the variables will change and the escaping becomes ineffective. It's just a problem waiting to happen, and the only safe way is to use prepared statements.

**Comment by matthewfranglen** [comment]
thanks for the explanation and link :+1:
