### ISSUE TITLE
Interface should provide links to questions/answers

### ISSUE THREAD

**Issue by gms8994** [laurent22/so-sql-injections#2]
Since we're pointing out SQL Injections on StackOverflow, links to the questions/answers should be provided so that comments could be placed on them suggesting a more secure way to achieve the goal.

Also, I noticed that this is primarily focused on questions, and doesn't yet include answers in the report, which is, in my opinion, actually more important, since people tend to copy and paste from SO.

**Comment by laurent22** [comment]
Good point for the question link - since the data was already there I've added it in the latest version (the date is now clickable).

I'm currently not planning to include the answers since it was mainly the questions that interested me, but I don't mind taking pull requests if someone wants to add this feature.
